server:
  port: 8080
  servlet:
    context-path: /optima

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/optima-project-retail-manager"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true